/** Preset names for admin „Adaugă oraș” (display + DB name). */
export const ROMANIAN_MAJOR_CITIES_ADMIN: readonly string[] = [
    "București",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Brașov",
    "Constanța",
    "Oradea",
    "Sibiu",
    "Craiova",
    "Ploiești",
    "Arad",
    "Baia Mare",
    "Bacău",
    "Suceava",
    "Târgu Mureș",
    "Bistrița",
    "Satu Mare",
    "Alba Iulia",
    "Deva",
    "Piatra Neamț",
    "Zalău",
    "Buzău",
    "Galați",
    "Brăila",
    "Râmnicu Vâlcea",
] as const;
